Traceback (most recent call last):
  File "bot_with_error.py", line 5, in <module>
    print("Hello, " + name
TypeError: greet() missing 1 required positional argument: 'name'
